---
- hosts: all
  gather_facts: no

  pre_tasks:
    - name: Install Python2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      become: yes
  
  tasks:
  - name: Install nodejs
    apt: name=nodejs state=present update_cache=true
    become: yes
  
  #- name: Install node
  #  apt: name=node state=present update_cache=true
  #  become: yes
  
  - name: Install npm
    apt: name=npm state=present update_cache=true
    become: yes
  
  - name: Install n
    npm: name=n global=yes state=present
    become: yes
  
  - command: n stable
    become: yes

  - name: Install forever
    npm: name=forever state=present global=yes
    become: yes
  
  - name: Install git
    apt: name=git state=present update_cache=true
    become: yes
  
  - name: Clone git repo
    git: repo=git@github.ncsu.edu:nkumar8/CSC510_F17_Project.git dest=CSC510_F17_Project/ clone=yes update=yes accept_hostkey=yes
  
  - name: Install npm packages
    command: npm install chdir=CSC510_F17_Project/SciBot/
    become: yes
